// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfl-JRuvnP_JOTNrtdP7pNBd1nhmyU8Mo',
    appId: '1:394088769302:web:88c46b770912b51e5c9237',
    messagingSenderId: '394088769302',
    projectId: 'e-comm-app-aaab7',
    authDomain: 'e-comm-app-aaab7.firebaseapp.com',
    storageBucket: 'e-comm-app-aaab7.firebasestorage.app',
    measurementId: 'G-Y8QM9FLT0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmHJzQhSIqYMmVcLMZ2ou6uttMItq7uzw',
    appId: '1:394088769302:android:92bc5c5e1ff997835c9237',
    messagingSenderId: '394088769302',
    projectId: 'e-comm-app-aaab7',
    storageBucket: 'e-comm-app-aaab7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9KFJgsS2VhDGzD7mXhW_HPzYg7bu22Vo',
    appId: '1:394088769302:ios:5fd1f87824ec21f25c9237',
    messagingSenderId: '394088769302',
    projectId: 'e-comm-app-aaab7',
    storageBucket: 'e-comm-app-aaab7.firebasestorage.app',
    androidClientId: '394088769302-qmn0j1u16d3d5t4q29goder0tobea8pj.apps.googleusercontent.com',
    iosClientId: '394088769302-6jfd8dkor21q5k3d6nij68nvo9dhmhpf.apps.googleusercontent.com',
    iosBundleId: 'com.sptpra.eCommApp',
  );

}